import React from 'react';
import {useNavigate} from 'react-router-dom';
import {ArrowUpRight,ChevronLeft,ChevronRight} from 'lucide-react';
import {Order,date,money} from '../lib/api';
import {Badge,Avatar,IconBtn,Empty} from './Common';
export const OrderTable=({orders,compact=false,finance=false}: {orders:Order[];compact?:boolean;finance?:boolean})=>{
 const navigate=useNavigate();const [page,setPage]=React.useState(1);const count=compact?6:10;
 React.useEffect(()=>setPage(1),[orders]);
 if(!orders.length)return <Empty text="Nenhuma ordem por aqui ainda."/>;
 return <div className="panel"><table className="order-table" data-testid="orders-table"><thead><tr><th style={{width:'9%'}}>ORDEM</th><th style={{width:'20%'}}>CLIENTE</th><th className="hide-mobile" style={{width:'21%'}}>EQUIPAMENTO / SERVIÇO</th><th className="status-col" style={{width:'19%'}}>{finance?'PAGAMENTO':'STATUS'}</th><th className="hide-mobile hide-medium" style={{width:'17%'}}>{finance?'TOTAL / RECEBIDO':'RESPONSÁVEL'}</th><th className="hide-mobile" style={{width:'10%'}}>{finance?'SALDO':'ENTRADA'}</th><th className="action-col" style={{width:'4%'}}/></tr></thead><tbody>{orders.slice((page-1)*count,page*count).map(o=><tr key={o.id} data-testid={`order-row-${o.number}`} onClick={()=>navigate(`/orders/${o.id}`)}><td><span className="order-number" data-testid={`order-number-${o.id}`}>#{o.number}</span></td><td><div className="customer-cell"><Avatar name={o.client_name} size="tiny" id={`client-avatar-${o.id}`}/><div data-testid={`order-client-${o.id}`}>{o.client_name}<small>{finance?o.item:`Cliente ${String(o.number-1000).padStart(3,'0')}`}</small></div></div></td><td className="hide-mobile item-name" data-testid={`order-item-${o.id}`}>{o.item}</td><td>{finance?<span data-testid={`payment-status-${o.id}`} className={`finance-${o.paid&&o.paid>=o.total?'paid':o.paid?'partial':'unpaid'}`}>{o.paid&&o.paid>=o.total?'● Pago':o.paid?'● Parcial':'● Não pago'}</span>:<Badge status={o.status} id={o.id}/>}</td><td className="hide-mobile hide-medium">{finance?<span data-testid={`order-total-${o.id}`}>{money(o.total)}<small className="muted" style={{display:'block',fontSize:9}}>{money(o.paid)} recebido</small></span>:<div className="table-technician"><Avatar name={o.technician_name} size="tiny" id={`tech-avatar-${o.id}`}/><span data-testid={`order-technician-${o.id}`}>{o.technician_name.split(' ').slice(0,2).join(' ')}</span></div>}</td><td className="hide-mobile muted" data-testid={`order-date-balance-${o.id}`}>{finance?money(o.total-(o.paid||0)):date(o.created_at)}</td><td><IconBtn testId={`open-order-${o.number}`} label={`Abrir ordem ${o.number}`} onClick={(e:any)=>{e.stopPropagation();navigate(`/orders/${o.id}`);}}><ArrowUpRight size={15}/></IconBtn></td></tr>)}</tbody></table><div className="table-footer"><span data-testid="orders-pagination-info">Exibindo {Math.min((page-1)*count+1,orders.length)}–{Math.min(page*count,orders.length)} de {orders.length} ordens de serviço</span><div className="table-foot-actions"><IconBtn testId="previous-page" label="Página anterior" disabled={page===1} onClick={()=>setPage(page-1)}><ChevronLeft size={13}/></IconBtn><span data-testid="current-page">{page}</span><IconBtn testId="next-page" label="Próxima página" disabled={page*count>=orders.length} onClick={()=>setPage(page+1)}><ChevronRight size={13}/></IconBtn></div></div></div>
};