import React,{useState,useEffect} from 'react';
import {useNavigate} from 'react-router-dom';
import {Plus} from 'lucide-react';
import {api,errorText} from '../lib/api';
import {useSession} from '../lib/session';
import {Modal,Field,Select,Btn} from './Common';
import {ClientForm} from './ClientForm';
import {toast} from 'sonner';
export const DynamicField=({field,prefix}:any)=><Field label={field.name} id={`${prefix}-${field.id}`}>{field.type==='select'?<Select id={`${prefix}-${field.id}`} name={`${prefix}:${field.id}`}><option value="">Selecione</option>{field.options.map((o:string)=><option key={o}>{o}</option>)}</Select>:<input id={`${prefix}-${field.id}`} data-testid={`${prefix}-${field.id}`} name={`${prefix}:${field.id}`} type={field.type==='number'?'number':field.type==='date'?'date':'text'} step={field.type==='number'?'any':undefined}/>}</Field>;
export const OrderForm=({open,onClose}:any)=>{
 const {session}=useSession();const navigate=useNavigate();const [clients,setClients]=useState<any[]>([]),[users,setUsers]=useState<any[]>([]),[selected,setSelected]=useState(''),[newClient,setNewClient]=useState(false),[busy,setBusy]=useState(false);
 useEffect(()=>{if(open)Promise.all([api.get('/clients'),api.get('/users')]).then(([c,u])=>{setClients(c.data);setUsers(u.data);}).catch(e=>toast.error(errorText(e)));},[open]);
 const submit=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const fd=new FormData(e.currentTarget);const values:any={item_fields:{},custom_values:{}};fd.forEach((v,k)=>{if(k.startsWith('template:'))values.item_fields[k.split(':')[1]]=v;else if(k.startsWith('custom:'))values.custom_values[k.split(':')[1]]=v;else values[k]=v;});setBusy(true);try{const r=await api.post('/orders',values);toast.success(`OS #${r.data.number} criada`);onClose();navigate(`/orders/${r.data.id}`);}catch(e){toast.error(errorText(e));}finally{setBusy(false);}};
 return <><Modal open={open&&!newClient} onClose={onClose} title="Nova ordem de serviço" description={session.template.name} id="new-order-modal"><form onSubmit={submit}><div className="form-grid"><div className="full"><Field label="Cliente" id="order-client"><div style={{display:'flex',gap:9}}><Select id="order-client" name="client_id" required value={selected} onChange={(e:any)=>setSelected(e.target.value)}><option value="">Selecione o cliente</option>{clients.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</Select><Btn secondary type="button" testId="order-add-client" onClick={()=>setNewClient(true)}><Plus size={16}/><span>Novo</span></Btn></div></Field></div><div className="full"><Field id="order-item" name="item" label={session.template.item_label} placeholder="Ex.: iPhone 13 Pro, 128 GB" required minLength={2}/></div>{session.template.fields.map((f:any)=><DynamicField key={f.id} field={f} prefix="template"/>)}<div className="full"><Field label="Problema relatado" id="order-problem"><textarea id="order-problem" data-testid="order-problem" name="problem" required minLength={3} placeholder="Relato do cliente e condições de entrada"/></Field></div><Field label="Técnico responsável" id="order-technician"><Select id="order-technician" name="technician_id" defaultValue={session.user.role==='technician'?session.user.id:''}><option value="">Não atribuído</option>{users.map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</Select></Field><Field label="Prioridade" id="order-priority"><Select id="order-priority" name="priority"><option value="normal">Normal</option><option value="high">Alta</option><option value="urgent">Urgente</option></Select></Field><Field label="Previsão de entrega" id="order-due-date" name="due_date" type="date"/>{session.company.custom_fields.length>0&&<h3 className="form-subtitle">Informações adicionais</h3>}{session.company.custom_fields.map((f:any)=><DynamicField key={f.id} field={f} prefix="custom"/>)}</div><div className="form-actions"><Btn secondary testId="order-cancel" type="button" onClick={onClose}>Cancelar</Btn><Btn testId="order-submit" type="submit" disabled={busy}>{busy?'Criando...':'Criar ordem de serviço'}</Btn></div></form></Modal><ClientForm open={newClient} onClose={()=>setNewClient(false)} onSaved={(c:any)=>{setClients([...clients,c]);setSelected(c.id);}}/></>
};