import React,{useEffect,useState} from 'react';
import {Plus,Trash2,Save,ReceiptText} from 'lucide-react';
import {api,money,errorText} from '../lib/api';
import {Btn,Field,IconBtn} from './Common';
import {toast} from 'sonner';
export const QuoteEditor=({order,onSaved}:any)=>{
 const [diagnosis,setDiagnosis]=useState(order.diagnosis||''),[lines,setLines]=useState<any[]>(order.quote?.length?order.quote:[{description:'',quantity:1,unit_price:0}]),[busy,setBusy]=useState(false);const editable=['diagnosis','rejected'].includes(order.status);
 useEffect(()=>{setDiagnosis(order.diagnosis||'');setLines(order.quote?.length?order.quote:[{description:'',quantity:1,unit_price:0}]);},[order.id,order.version,order.diagnosis,order.quote]);
 const update=(i:number,k:string,v:any)=>setLines(lines.map((l,j)=>j===i?{...l,[k]:v}:l));
 const save=async(e:any)=>{e.preventDefault();setBusy(true);try{await api.put(`/orders/${order.id}/quote`,{diagnosis,quote:lines});toast.success('Orçamento salvo');onSaved();}catch(e){toast.error(errorText(e));}finally{setBusy(false);}};
 return <section className="detail-section"><h2 data-testid="quote-section-title"><ReceiptText size={16}/>Diagnóstico e orçamento</h2>{editable?<form onSubmit={save} className="form-stack"><Field label="Diagnóstico técnico" id="quote-diagnosis"><textarea id="quote-diagnosis" data-testid="quote-diagnosis" value={diagnosis} onChange={e=>setDiagnosis(e.target.value)} required minLength={3} placeholder="Descreva a avaliação técnica e o serviço necessário"/></Field>{lines.map((l,i)=><div className="quote-line" key={i}><Field label={i===0?'Serviço / peça':undefined} id={`quote-description-${i}`} value={l.description} onChange={(e:any)=>update(i,'description',e.target.value)} placeholder="Descrição do serviço" required minLength={2}/><Field label={i===0?'Qtd.':undefined} id={`quote-quantity-${i}`} type="number" min="0.01" step="0.01" value={l.quantity} onChange={(e:any)=>update(i,'quantity',Number(e.target.value))} required/><Field label={i===0?'Valor unitário':undefined} id={`quote-price-${i}`} type="number" min="0" step="0.01" value={l.unit_price} onChange={(e:any)=>update(i,'unit_price',Number(e.target.value))} required/><IconBtn testId={`remove-quote-line-${i}`} type="button" label="Remover item" disabled={lines.length===1} onClick={()=>setLines(lines.filter((_,j)=>j!==i))}><Trash2 size={14}/></IconBtn></div>)}<div><Btn secondary small type="button" testId="add-quote-line" onClick={()=>setLines([...lines,{description:'',quantity:1,unit_price:0}])}><Plus size={13}/>Adicionar item</Btn></div><div className="quote-total"><span>Total do orçamento</span><strong data-testid="quote-total">{money(lines.reduce((a,l)=>a+l.quantity*l.unit_price,0))}</strong></div><Btn type="submit" testId="save-quote-button" disabled={busy}><Save size={15}/>{busy?'Salvando...':'Salvar diagnóstico e orçamento'}</Btn></form>:<><p data-testid="diagnosis-text">{order.diagnosis||'Diagnóstico ainda não registrado.'}</p><div className="quote-preview mt">{order.quote?.map((l:any,i:number)=><div key={i} data-testid={`quote-preview-line-${i}`}><span>{l.description}<small style={{display:'block'}}>{l.quantity} × {money(l.unit_price)}</small></span><span>{money(l.quantity*l.unit_price)}</span></div>)}<div><strong>Total do orçamento</strong><strong data-testid="quote-preview-total">{money(order.total)}</strong></div></div></>}</section>
};
