import React,{useState,useEffect} from 'react';
import {Plus,Pencil,Users,Mail,Phone} from 'lucide-react';
import {api,errorText} from '../lib/api';
import {PageHead,Btn,SearchBox,Avatar,IconBtn,Empty,Loading} from '../components/Common';
import {ClientForm} from '../components/ClientForm';
import {toast} from 'sonner';
export default function Clients(){
 const [clients,setClients]=useState<any[]>([]),[search,setSearch]=useState(''),[open,setOpen]=useState(false),[editing,setEditing]=useState<any>(null),[loaded,setLoaded]=useState(false);
 const load=()=>api.get('/clients').then(r=>{setClients(r.data);setLoaded(true);}).catch(e=>toast.error(errorText(e)));useEffect(()=>{load();},[]);
 const filtered=clients.filter(c=>`${c.name} ${c.email} ${c.phone}`.toLowerCase().includes(search.toLowerCase()));
 return <><PageHead title="Clientes" description={`${clients.length} clientes na sua base. Relacionamentos que fazem a diferença.`}><Btn testId="new-client-button" onClick={()=>{setEditing(null);setOpen(true);}}><Plus size={16}/>Novo cliente</Btn></PageHead><div className="filters-bar"><SearchBox id="clients-search" value={search} onChange={setSearch} placeholder="Buscar por nome, e-mail ou telefone..."/></div>{!loaded?<Loading/>:!filtered.length?<Empty text="Nenhum cliente encontrado."/>:<div className="panel"><table className="order-table" data-testid="clients-table"><thead><tr><th style={{width:'32%'}}>CLIENTE</th><th className="hide-mobile" style={{width:'25%'}}>E-MAIL</th><th style={{width:'24%'}}>WHATSAPP</th><th className="hide-mobile" style={{width:'14%'}}>CONSENTIMENTO</th><th style={{width:'5%'}}/></tr></thead><tbody>{filtered.map(c=><tr key={c.id} data-testid={`client-row-${c.id}`} onClick={()=>{setEditing(c);setOpen(true);}}><td><div className="customer-cell"><Avatar name={c.name} id={`clients-avatar-${c.id}`}/><div data-testid={`client-name-${c.id}`}>{c.name}<small>{c.document||'Pessoa / empresa'}</small></div></div></td><td className="hide-mobile muted" data-testid={`client-email-${c.id}`}>{c.email||'—'}</td><td className="muted" data-testid={`client-phone-${c.id}`}>{c.phone||'—'}</td><td className="hide-mobile" data-testid={`client-consent-${c.id}`}><span className={c.whatsapp_consent?'connected':'muted'}>{c.whatsapp_consent?'Autorizado':'Não informado'}</span></td><td><IconBtn testId={`edit-client-${c.id}`} label="Editar cliente" onClick={(e:any)=>{e.stopPropagation();setEditing(c);setOpen(true);}}><Pencil size={14}/></IconBtn></td></tr>)}</tbody></table></div>}<ClientForm key={editing?.id||'new'} open={open} onClose={()=>setOpen(false)} onSaved={load} client={editing}/></>
}