import React,{useState,useEffect} from 'react';
import {useSearchParams,useNavigate} from 'react-router-dom';
import {Plus,LayoutGrid,List,Clock,ArrowUpRight} from 'lucide-react';
import {api,Order,statuses,date,errorText} from '../lib/api';
import {useSession} from '../lib/session';
import {PageHead,Btn,SearchBox,Badge,Avatar,Select,Loading,Empty} from '../components/Common';
import {OrderTable} from '../components/OrderTable';
import {OrderForm} from '../components/OrderForm';
import {toast} from 'sonner';
export default function Orders(){
 const {session}=useSession();const [params,setParams]=useSearchParams();const [orders,setOrders]=useState<Order[]>([]),[loaded,setLoaded]=useState(false),[search,setSearch]=useState(''),[status,setStatus]=useState(''),[view,setView]=useState('list'),[mine,setMine]=useState(false);const navigate=useNavigate();
 const load=()=>api.get('/orders').then(r=>{setOrders(r.data);setLoaded(true);}).catch(e=>toast.error(errorText(e)));useEffect(()=>{load();},[]);
 const filtered=orders.filter(o=>(!status||o.status===status)&&(!mine||o.technician_id===session.user.id)&&`${o.number} ${o.client_name} ${o.item}`.toLowerCase().includes(search.toLowerCase()));
 return <><PageHead title="Ordens de serviço" description="Cada etapa sob controle. Do primeiro contato à entrega."><Btn testId="new-order-button" onClick={()=>setParams({new:'1'})}><Plus size={16}/>Nova ordem de serviço</Btn></PageHead><div className="status-tabs">{[['','Todas'],['open','Abertas'],['diagnosis','Em diagnóstico'],['awaiting','Aguardando aprovação'],['in_progress','Em execução'],['completed','Concluídas']].map(([s,label])=><button data-testid={`order-filter-${s||'all'}`} key={s} className={status===s?'selected':''} onClick={()=>setStatus(s)}>{label}<span>{orders.filter(o=>!s||o.status===s).length}</span></button>)}</div><div className="filters-bar"><SearchBox id="orders-search" value={search} onChange={setSearch} placeholder="Buscar por número, cliente ou item..."/><Select id="orders-status-select" aria-label="Filtrar status" value={status} onChange={(e:any)=>setStatus(e.target.value)}><option value="">Todos os status</option>{Object.entries(statuses).map(([k,v])=><option key={k} value={k}>{v}</option>)}</Select><Select id="orders-assignment-filter" aria-label="Responsável" value={mine?'mine':'all'} onChange={(e:any)=>setMine(e.target.value==='mine')}><option value="all">Todos os responsáveis</option><option value="mine">Minhas ordens</option></Select><div className="view-switch"><button data-testid="list-view-button" className={view==='list'?'selected':''} onClick={()=>setView('list')}><List size={16}/><span>Lista</span></button><button data-testid="kanban-view-button" className={view==='kanban'?'selected':''} onClick={()=>setView('kanban')}><LayoutGrid size={15}/><span>Kanban</span></button></div></div>{!loaded?<Loading/>:view==='list'?<OrderTable orders={filtered}/>:<div className="kanban" data-testid="orders-kanban">{Object.entries(statuses).filter(([s])=>status?s===status:!['delivered','cancelled','rejected'].includes(s)||filtered.some(o=>o.status===s)).map(([s,label])=><section className="kanban-column" key={s}><div className="kanban-title" data-testid={`kanban-column-${s}`}>{label}<span>{filtered.filter(o=>o.status===s).length}</span></div>{filtered.filter(o=>o.status===s).map(o=><button className="kanban-card" data-testid={`kanban-order-${o.number}`} key={o.id} onClick={()=>navigate(`/orders/${o.id}`)}><div><span className="order-number">#{o.number}</span><span className={`priority-${o.priority}`}>{o.priority==='urgent'?'● Urgente':o.priority==='high'?'● Alta':'Normal'}</span></div><h3>{o.item}</h3><p>{o.client_name}</p><div className="card-foot"><span><Clock size={11} style={{display:'inline',marginRight:4}}/>{date(o.due_date)}</span><Avatar name={o.technician_name} size="tiny" id={`kanban-avatar-${o.id}`}/></div></button>)}</section>)}</div>}<OrderForm open={params.get('new')==='1'} onClose={()=>setParams({})}/></>
}