import React,{useEffect,useState} from 'react';
import {BarChart3,Clock3,CheckCircle2,Wallet,CalendarDays} from 'lucide-react';
import {api,money,errorText,statuses} from '../lib/api';
import {PageHead,Stat,Loading,Select,Avatar,Empty} from '../components/Common';
import {toast} from 'sonner';
export default function Reports(){
 const [data,setData]=useState<any>(null),[days,setDays]=useState(30);useEffect(()=>{api.get(`/dashboard?days=${days}`).then(r=>setData(r.data)).catch(e=>toast.error(errorText(e)));},[days]);
 if(!data)return <Loading/>;
 return <><PageHead title="Relatórios" description="Os números que ajudam você a tomar as próximas decisões."><div className="period-select"><CalendarDays size={15}/><Select id="reports-period" value={days} onChange={(e:any)=>setDays(Number(e.target.value))}><option value={7}>Últimos 7 dias</option><option value={30}>Últimos 30 dias</option><option value={90}>Últimos 90 dias</option></Select></div></PageHead><div className="stats-grid"><Stat id="report-orders" label="Ordens no período" value={data.total} detail="Pela data de abertura" icon={BarChart3}/><Stat id="report-avg" label="Tempo de conclusão" value={`${data.avg_days} dias`} detail="Média dos serviços concluídos" icon={Clock3} tone="amber"/><Stat id="report-completed" label="Taxa de conclusão" value={`${data.total?Math.round(data.completed/data.total*100):0}%`} detail={`${data.completed} serviços concluídos`} icon={CheckCircle2} tone="green"/><Stat id="report-revenue" label="Receita recebida" value={money(data.revenue)} detail="Pela data do pagamento" icon={Wallet} tone="violet"/></div><div className="report-summary"><section className="detail-section"><h2 data-testid="report-productivity-title">Produtividade por responsável</h2>{data.productivity.map((t:any)=><div className="tech-row" key={t.id} data-testid={`report-tech-${t.id}`}><Avatar name={t.name} id={`report-avatar-${t.id}`}/><div className="tech-info"><strong>{t.name}</strong><small>{t.completed} concluídas / {t.assigned} atribuídas</small></div><div className="progress-track"><div style={{width:`${t.assigned?t.completed/t.assigned*100:0}%`}}/></div><span>{t.assigned?Math.round(t.completed/t.assigned*100):0}%</span></div>)}</section><section className="detail-section"><h2 data-testid="report-status-title">Distribuição de status</h2>{Object.entries(data.counts).map(([key,count]:any)=><div className="notification-row" key={key} data-testid={`report-count-${key}`}><span>{statuses[key]}</span><strong>{count}</strong></div>)}</section></div><section className="detail-section mt"><h2 data-testid="report-cancellation-title">Cancelamentos no período</h2>{data.cancellations.length?data.cancellations.map((o:any)=><div className="notification-row" key={o.id} data-testid={`report-cancelled-${o.id}`}><span>#{o.number} · {o.client_name}<small>{o.cancel_reason}</small></span><span>{money(o.total)}</span></div>):<p data-testid="report-no-cancellations">Nenhuma ordem cancelada neste período.</p>}</section></>
}