import React,{useState,useEffect} from 'react';
import {Plus,UserRoundX,Shield,Users} from 'lucide-react';
import {api,errorText} from '../lib/api';
import {useSession} from '../lib/session';
import {PageHead,Btn,Avatar,IconBtn,Modal,Field,Select} from '../components/Common';
import {toast} from 'sonner';
export default function Team(){
 const {session}=useSession();const [users,setUsers]=useState<any[]>([]),[open,setOpen]=useState(false),[busy,setBusy]=useState(false),[removing,setRemoving]=useState<any>(null);
 const load=()=>api.get('/users').then(r=>setUsers(r.data)).catch(e=>toast.error(errorText(e)));useEffect(()=>{load();},[]);
 const submit=async(e:any)=>{e.preventDefault();setBusy(true);try{await api.post('/users',Object.fromEntries(new FormData(e.currentTarget)));toast.success('Pessoa adicionada à equipe');load();setOpen(false);}catch(e){toast.error(errorText(e));}finally{setBusy(false);}};
 return <><PageHead title="Equipe" description={`${users.length} pessoas trabalhando para deixar tudo em ordem.`}><Btn testId="add-team-member" onClick={()=>setOpen(true)}><Plus size={16}/>Adicionar pessoa</Btn></PageHead><div className="team-grid">{users.map(u=><article className="team-card" key={u.id} data-testid={`team-member-${u.id}`}><div><Avatar name={u.name} id={`team-avatar-${u.id}`}/>{u.id!==session.user.id&&<IconBtn testId={`remove-member-${u.id}`} label="Remover acesso" onClick={()=>setRemoving(u)}><UserRoundX size={17}/></IconBtn>}</div><h2 data-testid={`team-name-${u.id}`}>{u.name}{u.id===session.user.id?' (você)':''}</h2><p data-testid={`team-email-${u.id}`}>{u.email}</p><span className="role-label" data-testid={`team-role-${u.id}`}>{u.role==='admin'?'Administrador':'Técnico'}</span></article>)}</div><Modal open={open} onClose={()=>setOpen(false)} title="Adicionar pessoa à equipe" id="team-modal"><form onSubmit={submit} className="form-stack"><Field id="team-name" label="Nome completo" name="name" required minLength={2}/><Field id="team-email" label="E-mail de acesso" name="email" type="email" required/><Field id="team-password" label="Senha de acesso" name="password" type="password" minLength={8} maxLength={64} required/><Field id="team-role" label="Permissão"><Select id="team-role" name="role"><option value="technician">Técnico — operação de ordens</option><option value="admin">Administrador — acesso completo</option></Select></Field><div className="form-actions"><Btn testId="team-submit" type="submit" disabled={busy}>Adicionar à equipe</Btn></div></form></Modal><Modal open={!!removing} onClose={()=>setRemoving(null)} title="Remover acesso à empresa" id="remove-team-modal"><p data-testid="remove-team-confirmation" className="muted" style={{fontSize:13}}>Remover o acesso de {removing?.name}? O histórico dos serviços será mantido.</p><div className="form-actions"><Btn secondary testId="keep-team-member" onClick={()=>setRemoving(null)}>Manter acesso</Btn><Btn testId="confirm-remove-member" onClick={async()=>{try{await api.delete(`/users/${removing.id}`);setRemoving(null);load();toast.success('Acesso removido');}catch(e){toast.error(errorText(e));}}}>Remover acesso</Btn></div></Modal></>
}